name: build and push Docker images

on:
  release:
    types: [published]

jobs:
  # ------------------
  #       BASE
  # ------------------

  base:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./base
          push: true
          tags: |
            brineylab/base:latest
            brineylab/base:${{ github.event.release.tag_name }}

  # ------------------
  #     PYTHON
  # ------------------

  # python image depends on base, and need to wait for base to proceed
  python:
    runs-on: ubuntu-latest
    needs: [base]

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./python
          push: true
          tags: |
            brineylab/python:latest
            brineylab/python:${{ github.event.release.tag_name }}

  # ------------------
  #     JUPYTER
  # ------------------

  # jupyter depends on python and needs to wait to be built
  jupyter:
    runs-on: ubuntu-latest
    needs: [python]

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./jupyter
          push: true
          tags: |
            brineylab/jupyter:latest
            brineylab/jupyter:${{ github.event.release.tag_name }}

  # datascience image depends on jupyter
  datascience:
    runs-on: ubuntu-latest
    needs: [jupyter]

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./datascience
          push: true
          tags: |
            brineylab/datascience:latest
            brineylab/datascience:${{ github.event.release.tag_name }}

  # deeplearning image depends on datascience
  deeplearning:
    runs-on: ubuntu-latest
    needs: [datascience]

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./deeplearning
          push: true
          tags: |
            brineylab/deeplearning:latest
            brineylab/deeplearning:${{ github.event.release.tag_name }}

  # ------------------
  #    CODESERVER
  # ------------------

  # codeserver image depends on python
  codeserver:
    runs-on: ubuntu-latest
    needs: [base]

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./codeserver
          push: true
          tags: |
            brineylab/codeserver:latest
            brineylab/codeserver:${{ github.event.release.tag_name }}
