name: build and push Docker images for Kubeflow

on:
  release:
    types: [published]

jobs:
  # ------------------
  #       BASE
  # ------------------

  base:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./kubeflow/base
          push: true
          tags: |
            brineylab/kubeflow-base:latest
            brineylab/kubeflow-base:${{ github.event.release.tag_name }}

  # ------------------
  #     PYTHON
  # ------------------

  # python image depends on base, and need to wait for base to proceed
  python:
    runs-on: ubuntu-latest
    needs: [base]

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./kubeflow/python
          push: true
          tags: |
            brineylab/kubeflow-python:latest
            brineylab/kubeflow-python:${{ github.event.release.tag_name }}

  # ------------------
  #     JUPYTER
  # ------------------

  # jupyter depends on python and needs to wait to be built
  jupyter:
    runs-on: ubuntu-latest
    needs: [python]

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./kubeflow/jupyter
          push: true
          tags: |
            brineylab/kubeflow-jupyter:latest
            brineylab/kubeflow-jupyter:${{ github.event.release.tag_name }}

  # datascience image depends on jupyter
  datascience:
    runs-on: ubuntu-latest
    needs: [jupyter]

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./kubeflow/datascience
          push: true
          tags: |
            brineylab/kubeflow-datascience:latest
            brineylab/kubeflow-datascience:${{ github.event.release.tag_name }}

  # deeplearning image depends on datascience
  deeplearning:
    runs-on: ubuntu-latest
    needs: [datascience]

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./kubeflow/deeplearning
          push: true
          tags: |
            brineylab/kubeflow-deeplearning:latest
            brineylab/kubeflow-deeplearning:${{ github.event.release.tag_name }}

  # ------------------
  #    CODESERVER
  # ------------------

  # codeserver image depends on python
  codeserver:
    runs-on: ubuntu-latest
    needs: [python]

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ./kubeflow/codeserver
          push: true
          tags: |
            brineylab/kubeflow-codeserver:latest
            brineylab/kubeflow-codeserver:${{ github.event.release.tag_name }}

  # # ------------------
  # #        R
  # # ------------------

  # # r image depends on base
  # r:
  #   runs-on: ubuntu-latest
  #   needs: [base]

  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3
  #     - name: set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     - name: set up docker buildx
  #       uses: docker/setup-buildx-action@v2
  #     - name: login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: build and push
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: ./r
  #         push: true
  #         tags: |
  #           brineylab/r:latest
  #           brineylab/r:${{ github.event.release.tag_name }}

  # # rstudio image depends on r
  # rstudio:
  #   runs-on: ubuntu-latest
  #   needs: [r]

  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3
  #     - name: set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     - name: set up docker buildx
  #       uses: docker/setup-buildx-action@v2
  #     - name: login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: build and push
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: ./rstudio
  #         push: true
  #         tags: |
  #           brineylab/rstudio:latest
  #           brineylab/rstudio:${{ github.event.release.tag_name }}
